# Generated by Django 2.2.7 on 2019-11-23 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='ImageData',
            fields=[
                ('data_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='secondBrainBackend.Data')),
                ('path', models.CharField(max_length=256)),
            ],
            bases=('secondBrainBackend.data',),
        ),
        migrations.CreateModel(
            name='NoteData',
            fields=[
                ('data_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='secondBrainBackend.Data')),
                ('text', models.CharField(max_length=256)),
            ],
            bases=('secondBrainBackend.data',),
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='secondBrainBackend.Data')),
                ('tags', models.ManyToManyField(related_name='information', to='secondBrainBackend.Tag')),
            ],
        ),
    ]
